export const MovieStatus = new Map([
    ["comingsoon", "Sắp chiếu"],
    ["ongoing", "Đang tiến hành"],
        ["completed", "Hoàn thành"]
]) 

export const MovieTabs = [{
    id: "category",
    name: "Thể loại",
    slug: "the-loai",
}, {
    id: "year",
    name: "Năm",
    slug: "nam",
}, {
    id: "country",
    name: "Quốc gia",
    slug: "quoc-gia",
}, {
    id: "series",
    name: "Phim bộ",
    slug: "phim-bo",
}, {
    id: "movie",
    name: "Phim lẻ",
    slug: "phim-le",
}, {
    id: "filter",
    name: "Lọc phim",
    slug: "loc-phim",
}];

export const Categories = [
    // "Phim Mới",
    // "Phim Bộ",
    // "Phim lẻ",
    // "TV Shows",
    // "Hoạt Hình",
    // "Phim Vietsub",
    // "Phim Thuyết Minh",
    // "Phim Lồng Tiếng",
    // "Phim Bộ Đang Chiếu",
    // "Phim Trọn Bộ",
    // "Phim Sắp Chiếu",
    "Hành Động",
    "Tình Cảm",
    "Hài Hước",
    "Cổ Trang",
    "Tâm Lý",
    "Hình Sự",
    "Chiến Tranh",
    "Thể Thao",
    "Võ Thuật",
    "Viễn Tưởng",
    "Phiêu Lưu",
    "Khoa Học",
    "Kinh Dị",
    "Âm Nhạc",
    "Thần Thoại",
    "Tài Liệu",
    "Gia Đình",
    "Chính kịch",
    "Bí ẩn",
    "Học Đường",
    "Kinh Điển",
];

export const years = ["2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023"];

export const countries = [
    "Trung Quốc",
    "Hàn Quốc",
    "Nhật Bản",
    "Thái Lan",
    "Âu Mỹ",
    "Đài Loan",
    "Hồng Kông",
    "Ấn Độ",
    "Anh",
    "Pháp",
    "Canada",
    "Quốc Gia Khác",
    "Đức",
    "Tây Ban Nha",
    "Thổ Nhĩ Kỳ",
    "Hà Lan",
    "Indonesia",
    "Nga",
    "Mexico",
    "Ba lan",
    "Úc",
    "Thụy Điển",
    "Malaysia",
    "Brazil",
    "Philippines",
    "Bồ Đào Nha",
    "Ý",
    "Đan Mạch",
    "UAE",
    "Na Uy",
    "Thụy Sĩ",
    "Châu Phi",
    "Nam Phi",
    "Ukraina",
    "Ả Rập Xê Út",
];
